# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QButtonGroup, QLabel, QLineEdit,
    QPushButton, QRadioButton, QSizePolicy, QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(543, 557)
        icon = QIcon()
        icon.addFile(u"blazing.png", QSize(), QIcon.Normal, QIcon.Off)
        Widget.setWindowIcon(icon)
        self.naslov = QLabel(Widget)
        self.naslov.setObjectName(u"naslov")
        self.naslov.setGeometry(QRect(20, 10, 331, 51))
        font = QFont()
        font.setPointSize(29)
        self.naslov.setFont(font)
        self.serviceValue = QLabel(Widget)
        self.serviceValue.setObjectName(u"serviceValue")
        self.serviceValue.setGeometry(QRect(30, 70, 131, 21))
        font1 = QFont()
        font1.setPointSize(15)
        font1.setBold(False)
        self.serviceValue.setFont(font1)
        self.leServiceValue = QLineEdit(Widget)
        self.leServiceValue.setObjectName(u"leServiceValue")
        self.leServiceValue.setGeometry(QRect(50, 100, 201, 31))
        self.euroSymbol = QLabel(Widget)
        self.euroSymbol.setObjectName(u"euroSymbol")
        self.euroSymbol.setGeometry(QRect(30, 100, 66, 31))
        font2 = QFont()
        font2.setPointSize(20)
        self.euroSymbol.setFont(font2)
        self.serviceValue_2 = QLabel(Widget)
        self.serviceValue_2.setObjectName(u"serviceValue_2")
        self.serviceValue_2.setGeometry(QRect(280, 70, 91, 21))
        self.serviceValue_2.setFont(font1)
        self.vipPrice = QLabel(Widget)
        self.vipPrice.setObjectName(u"vipPrice")
        self.vipPrice.setGeometry(QRect(280, 100, 121, 31))
        self.vipPrice.setFont(font2)
        self.popust7 = QRadioButton(Widget)
        self.buttonGroup1 = QButtonGroup(Widget)
        self.buttonGroup1.setObjectName(u"buttonGroup1")
        self.buttonGroup1.addButton(self.popust7)
        self.popust7.setObjectName(u"popust7")
        self.popust7.setGeometry(QRect(410, 90, 109, 24))
        self.popust10 = QRadioButton(Widget)
        self.buttonGroup1.addButton(self.popust10)
        self.popust10.setObjectName(u"popust10")
        self.popust10.setGeometry(QRect(410, 120, 109, 24))
        self.popust10.setChecked(True)
        self.popust12 = QRadioButton(Widget)
        self.buttonGroup1.addButton(self.popust12)
        self.popust12.setObjectName(u"popust12")
        self.popust12.setGeometry(QRect(410, 150, 109, 24))
        self.serviceValue_3 = QLabel(Widget)
        self.serviceValue_3.setObjectName(u"serviceValue_3")
        self.serviceValue_3.setGeometry(QRect(430, 30, 91, 21))
        self.serviceValue_3.setFont(font1)
        self.serviceValue_4 = QLabel(Widget)
        self.serviceValue_4.setObjectName(u"serviceValue_4")
        self.serviceValue_4.setGeometry(QRect(30, 150, 131, 21))
        self.serviceValue_4.setFont(font1)
        self.boosterCut = QLabel(Widget)
        self.boosterCut.setObjectName(u"boosterCut")
        self.boosterCut.setGeometry(QRect(70, 190, 171, 31))
        font3 = QFont()
        font3.setPointSize(28)
        self.boosterCut.setFont(font3)
        self.serviceValue_5 = QLabel(Widget)
        self.serviceValue_5.setObjectName(u"serviceValue_5")
        self.serviceValue_5.setGeometry(QRect(410, 190, 111, 21))
        self.serviceValue_5.setFont(font1)
        self.cut30 = QRadioButton(Widget)
        self.buttonGroup = QButtonGroup(Widget)
        self.buttonGroup.setObjectName(u"buttonGroup")
        self.buttonGroup.addButton(self.cut30)
        self.cut30.setObjectName(u"cut30")
        self.cut30.setGeometry(QRect(410, 230, 109, 24))
        self.cut30.setChecked(True)
        self.cut35 = QRadioButton(Widget)
        self.buttonGroup.addButton(self.cut35)
        self.cut35.setObjectName(u"cut35")
        self.cut35.setGeometry(QRect(410, 260, 109, 24))
        self.cut40 = QRadioButton(Widget)
        self.buttonGroup.addButton(self.cut40)
        self.cut40.setObjectName(u"cut40")
        self.cut40.setGeometry(QRect(410, 290, 109, 24))
        self.cut50 = QRadioButton(Widget)
        self.buttonGroup.addButton(self.cut50)
        self.cut50.setObjectName(u"cut50")
        self.cut50.setGeometry(QRect(410, 320, 109, 24))
        self.exit1 = QPushButton(Widget)
        self.exit1.setObjectName(u"exit1")
        self.exit1.setGeometry(QRect(410, 360, 101, 41))
        self.noteCopy = QPushButton(Widget)
        self.noteCopy.setObjectName(u"noteCopy")
        self.noteCopy.setGeometry(QRect(410, 410, 101, 41))
        self.popust0 = QRadioButton(Widget)
        self.buttonGroup1.addButton(self.popust0)
        self.popust0.setObjectName(u"popust0")
        self.popust0.setGeometry(QRect(410, 60, 109, 24))
        self.pcPlatform = QRadioButton(Widget)
        self.pcPlatform.setObjectName(u"pcPlatform")
        self.pcPlatform.setGeometry(QRect(30, 280, 109, 24))
        self.ps4Platform = QRadioButton(Widget)
        self.ps4Platform.setObjectName(u"ps4Platform")
        self.ps4Platform.setGeometry(QRect(30, 310, 109, 24))
        self.xboxPlatform = QRadioButton(Widget)
        self.xboxPlatform.setObjectName(u"xboxPlatform")
        self.xboxPlatform.setGeometry(QRect(30, 340, 131, 24))
        self.sherpaPlatform = QRadioButton(Widget)
        self.sherpaPlatform.setObjectName(u"sherpaPlatform")
        self.sherpaPlatform.setGeometry(QRect(30, 370, 109, 24))
        self.label = QLabel(Widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(230, 240, 111, 171))
        self.label.setPixmap(QPixmap(u"blazing.png"))
        self.boosterNote = QLineEdit(Widget)
        self.boosterNote.setObjectName(u"boosterNote")
        self.boosterNote.setGeometry(QRect(30, 470, 481, 31))
        self.noteValue = QLabel(Widget)
        self.noteValue.setObjectName(u"noteValue")
        self.noteValue.setGeometry(QRect(30, 520, 511, 31))
        font4 = QFont()
        font4.setPointSize(15)
        font4.setBold(True)
        font4.setUnderline(False)
        self.noteValue.setFont(font4)
        self.noteValue.setAutoFillBackground(True)
        self.copied = QLabel(Widget)
        self.copied.setObjectName(u"copied")
        self.copied.setGeometry(QRect(330, 420, 66, 18))
        font5 = QFont()
        font5.setBold(True)
        self.copied.setFont(font5)

        self.retranslateUi(Widget)

        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Widget", u"Blazingtron 1.0", None))
        self.naslov.setText(QCoreApplication.translate("Widget", u"VIP Blazingtron 1.0", None))
        self.serviceValue.setText(QCoreApplication.translate("Widget", u"Service Value:", None))
        self.euroSymbol.setText(QCoreApplication.translate("Widget", u"\u20ac", None))
        self.serviceValue_2.setText(QCoreApplication.translate("Widget", u"VIP price:", None))
        self.vipPrice.setText(QCoreApplication.translate("Widget", u"\u20ac0.00", None))
        self.popust7.setText(QCoreApplication.translate("Widget", u"  7% discount", None))
        self.popust10.setText(QCoreApplication.translate("Widget", u"10% discount", None))
        self.popust12.setText(QCoreApplication.translate("Widget", u"12% discount", None))
        self.serviceValue_3.setText(QCoreApplication.translate("Widget", u"Popust:", None))
        self.serviceValue_4.setText(QCoreApplication.translate("Widget", u"Boosters Cut:", None))
        self.boosterCut.setText(QCoreApplication.translate("Widget", u"\u20ac0.00", None))
        self.serviceValue_5.setText(QCoreApplication.translate("Widget", u"Booster cut:", None))
        self.cut30.setText(QCoreApplication.translate("Widget", u"30% Cut", None))
        self.cut35.setText(QCoreApplication.translate("Widget", u"35% Cut", None))
        self.cut40.setText(QCoreApplication.translate("Widget", u"40% Cut", None))
        self.cut50.setText(QCoreApplication.translate("Widget", u"50% Cut", None))
        self.exit1.setText(QCoreApplication.translate("Widget", u"Exit", None))
        self.noteCopy.setText(QCoreApplication.translate("Widget", u"Copy Note", None))
        self.popust0.setText(QCoreApplication.translate("Widget", u"  0% discount", None))
        self.pcPlatform.setText(QCoreApplication.translate("Widget", u"PC Platform", None))
        self.ps4Platform.setText(QCoreApplication.translate("Widget", u"PS4 Platform", None))
        self.xboxPlatform.setText(QCoreApplication.translate("Widget", u"XBOX Platform", None))
        self.sherpaPlatform.setText(QCoreApplication.translate("Widget", u"Sherpa", None))
        self.label.setText("")
        self.noteValue.setText(QCoreApplication.translate("Widget", u"-waiting-", None))
        self.copied.setText("")
    # retranslateUi

